import React from 'react';
import { Edit, CheckCircle, Play, Trash2 } from 'lucide-react';
import axios from 'axios';

const QuizList = ({ quizzes, onEdit, onRefresh }) => {

  const handleApprove = async (id) => {
    if (!window.confirm('Are you sure you want to approve this quiz?')) return;
    try {
      await axios.put(`http://localhost:5000/api/admin/quizzes/${id}/approve`);
      onRefresh();
    } catch (err) {
      alert(err.response?.data?.error || 'Approval failed');
    }
  };

  const handleActivate = async (quiz) => {
    const defaultDate = quiz.activeDate ? new Date(quiz.activeDate).toISOString().split('T')[0] : new Date().toISOString().split('T')[0];
    const dateStr = prompt(`Activate this quiz for which date? \nTo be visible to users on:`, defaultDate);
    if (!dateStr) return;
    try {
      await axios.put(`http://localhost:5000/api/admin/quizzes/${quiz._id}/activate`, { activeDate: dateStr });
      onRefresh();
    } catch (err) {
      alert(err.response?.data?.error || 'Activation failed');
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this quiz? This action cannot be undone.')) return;
    try {
      await axios.delete(`http://localhost:5000/api/admin/quizzes/${id}`);
      onRefresh();
    } catch (err) {
      alert(err.response?.data?.error || 'Deletion failed');
    }
  };

  const getStatusStyles = (status) => {
    switch (status) {
      case 'DRAFT': return 'bg-white/5 text-text-secondary border-text-secondary/50';
      case 'APPROVED': return 'bg-accent-primary/10 text-accent-primary border-accent-primary/50';
      case 'ACTIVE': return 'bg-success/10 text-success border-success/50';
      case 'ARCHIVED': return 'bg-error/10 text-error border-error/50';
      default: return 'bg-white/5 text-gray-400 border-gray-500/50';
    }
  };

  return (
    <div className="glass-card p-0 overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-white/[0.08] text-text-secondary">
              <th className="p-4 font-semibold">Status</th>
              <th className="p-4 font-semibold">Title</th>
              <th className="p-4 font-semibold">Generated By</th>
              <th className="p-4 font-semibold">Active Date</th>
              <th className="p-4 font-semibold">Actions</th>
            </tr>
          </thead>
          <tbody>
            {quizzes.map((quiz) => (
              <tr key={quiz._id} className="border-b border-white/[0.05] hover:bg-white/[0.02] transition-colors">
                <td className="p-4">
                  <span className={`px-3 py-1 rounded-full text-xs font-medium border ${getStatusStyles(quiz.status)}`}>
                    {quiz.status}
                  </span>
                </td>
                <td className="p-4 font-medium">{quiz.title}</td>
                <td className="p-4">
                  <span className="opacity-70">Manual</span>
                </td>
                <td className="p-4 text-text-secondary">
                   {quiz.activeDate ? new Date(quiz.activeDate).toLocaleDateString() : '-'}
                </td>
                <td className="p-4">
                  <div className="flex gap-3">
                    <button onClick={() => onEdit(quiz)} title="Edit" className="text-text-primary hover:text-accent-primary transition-colors">
                      <Edit size={18} />
                    </button>
                    
                    <button 
                      onClick={() => handleDelete(quiz._id)} 
                      title="Delete" 
                      className="text-text-secondary hover:text-error transition-colors"
                    >
                      <Trash2 size={18} />
                    </button>

                    {quiz.status === 'DRAFT' && (
                      <button onClick={() => handleApprove(quiz._id)} title="Approve" className="text-success hover:text-green-400 transition-colors">
                        <CheckCircle size={18} />
                      </button>
                    )}

                    {(quiz.status === 'DRAFT' || quiz.status === 'APPROVED') && (
                      <button 
                        onClick={() => handleActivate(quiz)} 
                        title={quiz.status === 'DRAFT' ? "Approve & Activate" : "Activate"}
                        className="text-accent-primary hover:text-indigo-400 transition-colors"
                      >
                        <Play size={18} />
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
            {quizzes.length === 0 && (
              <tr>
                <td colSpan="5" className="p-8 text-center text-text-secondary">
                  No quizzes found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default QuizList;
